# Generated by Django 3.2.7 on 2023-11-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
