# Generated by Django 4.2.7 on 2023-11-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_hashtag_post_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='content',
            new_name='body',
        ),
    ]
