# Generated by Django 4.2.7 on 2023-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_content_hashtag_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='body',
            new_name='description',
        ),
    ]
