# Generated by Django 4.2.7 on 2023-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_body_hashtag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
