# Generated by Django 4.2.7 on 2023-11-20 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
