# Generated by Django 4.2.7 on 2023-11-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_location_street_location_street_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='street',
            new_name='street_name',
        ),
    ]
